error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-08-03T07:23:15.255Z"}
error: 
    status - 500 
    message - ValidationError: "FirstName" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-08-03T07:46:50.538Z"}
error: 
    status - 500 
    message - ValidationError: "FirstName" length must be at least 4 characters long 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2022-08-04T03:07:08.497Z"}
error: 
    status - 500 
    message - ValidationError: "Password" length must be at least 8 characters long 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-08-07T19:14:13.644Z"}
error: uncaughtException: Cannot read properties of undefined (reading 'EmailId')
TypeError: Cannot read properties of undefined (reading 'EmailId')
    at D:\javascript\projects\Fundoo-Notes\FundooNotes\src\middlewares\/auth.middleware.js:29:32
    at D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\jsonwebtoken\verify.js:223:12
    at getSecret (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.verify (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (D:\javascript\projects\Fundoo-Notes\FundooNotes\src\middlewares\/auth.middleware.js:22:26)
    at tryCatch (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (D:\javascript\projects\Fundoo-Notes\FundooNotes\src\middlewares\/auth.middleware.js:12:22)
    at Layer.handle [as handle_request] (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\express\lib\router\route.js:144:13) {"date":"Mon Aug 08 2022 08:56:20 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":5425168},"process":{"argv":["node","D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\src\\index.js"],"cwd":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18399469,"external":19973206,"heapTotal":49307648,"heapUsed":44501648,"rss":82182144},"pid":107172,"uid":null,"version":"v16.15.1"},"stack":"TypeError: Cannot read properties of undefined (reading 'EmailId')\n    at D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\src\\middlewares\\/auth.middleware.js:29:32\n    at D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\jsonwebtoken\\verify.js:223:12\n    at getSecret (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\jsonwebtoken\\verify.js:90:14)\n    at Object.verify (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\jsonwebtoken\\verify.js:94:10)\n    at _callee$ (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\src\\middlewares\\/auth.middleware.js:22:26)\n    at tryCatch (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12\n    at userAuth (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\src\\middlewares\\/auth.middleware.js:12:22)\n    at Layer.handle [as handle_request] (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\express\\lib\\router\\route.js:144:13)","timestamp":"2022-08-08T03:26:20.760Z","trace":[{"column":32,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\src\\middlewares\\/auth.middleware.js","function":null,"line":29,"method":null,"native":false},{"column":12,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\jsonwebtoken\\verify.js","function":null,"line":223,"method":null,"native":false},{"column":14,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\jsonwebtoken\\verify.js","function":"getSecret","line":90,"method":null,"native":false},{"column":10,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\jsonwebtoken\\verify.js","function":"Object.verify","line":94,"method":"verify","native":false},{"column":26,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\src\\middlewares\\/auth.middleware.js","function":"_callee$","line":22,"method":null,"native":false},{"column":17,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":86,"method":null,"native":false},{"column":24,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator._invoke","line":66,"method":"_invoke","native":false},{"column":21,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.next","line":117,"method":"next","native":false},{"column":24,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_next","line":25,"method":null,"native":false},{"column":7,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":null,"line":32,"method":null,"native":false},{"column":null,"file":null,"function":"new Promise","line":null,"method":null,"native":false},{"column":12,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":null,"line":21,"method":null,"native":false},{"column":22,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\src\\middlewares\\/auth.middleware.js","function":"userAuth","line":12,"method":null,"native":false},{"column":5,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\express\\lib\\router\\layer.js","function":"Layer.handle [as handle_request]","line":95,"method":"handle [as handle_request]","native":false},{"column":13,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\express\\lib\\router\\route.js","function":"next","line":144,"method":null,"native":false}]}
error: uncaughtException: Authorization token is Incorrect
Error: Authorization token is Incorrect
    at D:\javascript\projects\Fundoo-Notes\FundooNotes\src\middlewares\/auth.middleware.js:24:15
    at D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\jsonwebtoken\verify.js:133:14
    at getSecret (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.verify (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (D:\javascript\projects\Fundoo-Notes\FundooNotes\src\middlewares\/auth.middleware.js:22:9)
    at tryCatch (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (D:\javascript\projects\Fundoo-Notes\FundooNotes\src\middlewares\/auth.middleware.js:12:22)
    at Layer.handle [as handle_request] (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\express\lib\router\route.js:144:13) {"date":"Mon Aug 08 2022 09:07:23 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":5425831},"process":{"argv":["node","D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\src\\index.js"],"cwd":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":19502854,"external":31624240,"heapTotal":81920000,"heapUsed":56232680,"rss":116920320},"pid":112188,"uid":null,"version":"v16.15.1"},"stack":"Error: Authorization token is Incorrect\n    at D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\src\\middlewares\\/auth.middleware.js:24:15\n    at D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\jsonwebtoken\\verify.js:133:14\n    at getSecret (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\jsonwebtoken\\verify.js:90:14)\n    at Object.verify (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\jsonwebtoken\\verify.js:94:10)\n    at _callee$ (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\src\\middlewares\\/auth.middleware.js:22:9)\n    at tryCatch (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12\n    at userAuth (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\src\\middlewares\\/auth.middleware.js:12:22)\n    at Layer.handle [as handle_request] (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\express\\lib\\router\\route.js:144:13)","timestamp":"2022-08-08T03:37:23.532Z","trace":[{"column":15,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\src\\middlewares\\/auth.middleware.js","function":null,"line":24,"method":null,"native":false},{"column":14,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\jsonwebtoken\\verify.js","function":null,"line":133,"method":null,"native":false},{"column":14,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\jsonwebtoken\\verify.js","function":"getSecret","line":90,"method":null,"native":false},{"column":10,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\jsonwebtoken\\verify.js","function":"Object.verify","line":94,"method":"verify","native":false},{"column":9,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\src\\middlewares\\/auth.middleware.js","function":"_callee$","line":22,"method":null,"native":false},{"column":17,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":86,"method":null,"native":false},{"column":24,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator._invoke","line":66,"method":"_invoke","native":false},{"column":21,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.next","line":117,"method":"next","native":false},{"column":24,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_next","line":25,"method":null,"native":false},{"column":7,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":null,"line":32,"method":null,"native":false},{"column":null,"file":null,"function":"new Promise","line":null,"method":null,"native":false},{"column":12,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":null,"line":21,"method":null,"native":false},{"column":22,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\src\\middlewares\\/auth.middleware.js","function":"userAuth","line":12,"method":null,"native":false},{"column":5,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\express\\lib\\router\\layer.js","function":"Layer.handle [as handle_request]","line":95,"method":"handle [as handle_request]","native":false},{"column":13,"file":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\node_modules\\express\\lib\\router\\route.js","function":"next","line":144,"method":null,"native":false}]}
error: uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>". {"date":"Mon Aug 08 2022 09:10:29 GMT+0530 (India Standard Time)","error":{"code":"ERR_UNHANDLED_REJECTION"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":5426016},"process":{"argv":["node","D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\src\\index.js"],"cwd":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18454562,"external":23169366,"heapTotal":81813504,"heapUsed":48927640,"rss":115220480},"pid":114756,"uid":null,"version":"v16.15.1"},"stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".","timestamp":"2022-08-08T03:40:29.147Z","trace":[]}
error: uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>". {"date":"Mon Aug 08 2022 09:11:14 GMT+0530 (India Standard Time)","error":{"code":"ERR_UNHANDLED_REJECTION"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":5426062},"process":{"argv":["node","D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\src\\index.js"],"cwd":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18446370,"external":23169212,"heapTotal":82075648,"heapUsed":48875104,"rss":115032064},"pid":87108,"uid":null,"version":"v16.15.1"},"stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".","timestamp":"2022-08-08T03:41:14.785Z","trace":[]}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.verify (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (D:\javascript\projects\Fundoo-Notes\FundooNotes\src\middlewares\/auth.middleware.js:22:9)
    at tryCatch (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (D:\javascript\projects\Fundoo-Notes\FundooNotes\src\middlewares\/auth.middleware.js:12:22)
    at Layer.handle [as handle_request] (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\express\lib\router\route.js:114:3) 
    url - /api/v1/notes 
    method - GET 
    IP - ::1
   {"timestamp":"2022-08-08T03:45:04.741Z"}
error: uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>". {"date":"Mon Aug 08 2022 09:15:10 GMT+0530 (India Standard Time)","error":{"code":"ERR_UNHANDLED_REJECTION"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":5426298},"process":{"argv":["node","D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes\\src\\index.js"],"cwd":"D:\\javascript\\projects\\Fundoo-Notes\\FundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18279725,"external":19853462,"heapTotal":50356224,"heapUsed":43964232,"rss":82268160},"pid":117592,"uid":null,"version":"v16.15.1"},"stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".","timestamp":"2022-08-08T03:45:10.426Z","trace":[]}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.verify (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (D:\javascript\projects\Fundoo-Notes\FundooNotes\src\middlewares\/auth.middleware.js:22:9)
    at tryCatch (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (D:\javascript\projects\Fundoo-Notes\FundooNotes\src\middlewares\/auth.middleware.js:12:22)
    at Layer.handle [as handle_request] (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\javascript\projects\Fundoo-Notes\FundooNotes\node_modules\express\lib\router\route.js:114:3) 
    url - /api/v1/notes 
    method - GET 
    IP - ::1
   {"timestamp":"2022-08-08T03:47:15.069Z"}
